StableDiffusion:

  CLIP:
    embed_dim: 768
    heads: 12
    vocab_size: 49408
    max_seq_len: 77
    mlp_expansion: 4
    num_layers: 12

  UNET:
    input_conv_channels: 320
    temb_channels: &a 1280
    heads: 12
    transformer2d_num_encoder_layers: 12
    normalisation_eps: 1e-6
    num_groups: 32
    time_mlp_channels: *a
    ff_expansion: 4
    upsample_scale_factor: 2

  VAE:
    num_groups: 32
    latent_channels: 4
    rgb_channels: &b 3

    encoder:
      num_downblocks: 4
      input_channels: 128
      output_channels: 512
      num_resnets: 2
      num_downsamplers: 1
      midblock_num_attn: 1

    decoder:
      num_upblocks: 4
      input_channels: 512
      output_channels: *b
      num_upblocks: 4
      num_resnets: 3
      num_upsamplers: 1
      upsample_scale_factor: 2
      midblock_num_attn: 1

    